### ISSUE TITLE
New Bagnon update makes the button not show up

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [LudiusMaximus/Bagnon_ReagentBankButton#1]
Bagnon_ReagentBankButton's button on the bank doesn't show up with the new Bagnon update released today

**Comment by Galthariel** [comment]
same

**Comment by LudiusMaximus** [comment]
Should be fixed with the latest version (1.11.0, https://www.curseforge.com/wow/addons/bagnon-reagentbankbutton/files/4531987) released yesterday?
