### ISSUE TITLE
Not Showing Reagent Button on version Bagnon_ReagentBankButton_1.11.0.

### ISSUE THREAD

**Issue by Galthariel** [LudiusMaximus/Bagnon_ReagentBankButton#2]
Using the latest version Bagnon_ReagentBankButton_1.11.0 and Reagent Button is not showing. I had to return to the previous version from 4/5/2023 to get the button back.

**Comment by LudiusMaximus** [comment]
I guess it worked after all? :-)

**Comment by Galthariel** [comment]
Yes, it did, For some reason, Curse didn't show me the updated version of Bagnon so I was using a fix people posted in the Bagnon site. The only issue now is with BagBrother Lua error. Hope the dev fixes soon. Tks much :-)
