### ISSUE TITLE
Error Encountered when loading WoW

### ISSUE THREAD

**Issue by LostinTime75** [LudiusMaximus/Bagnon_ReagentBankButton#3]
Date: 2024-01-07 00:07:00
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Bagnon_ReagentBankButton/main.lua line 158:
   hooksecurefunc(): ListMenuButtons is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Interface/AddOns/Bagnon_ReagentBankButton/main.lua"]:158: in main chunk
Locals:

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  Auctionator, v10.2.12
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BagBrother, v
  Bagnon, v10.2.12
  BagnonBoE, v2.0.74-Release
  BagnonChampion, v3.0
  BagnonCurrencies, v2.2.0
  BagnonGarbage, v2.0.61-Release
  BagnonItemInfo, v2.2.70-Release
  BagnonItemLevel, v2.0.85-Release
  BagnonReagentBankButton, v1.11.3
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  BlizRuntimeLib v10.2.0.52649(US) <enUS>
  (ck=27f)

**Comment by LudiusMaximus** [comment]
Thanks for letting me know. It seems that the last version of Bagnon has (finally) implemented a Reagents Bank button itself. The icon still seems to be buggy, but otherwise it works. So my addon here is no longer needed. :-)
