### ISSUE TITLE
Error with new Bagnon 10.2 update

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [LudiusMaximus/Bagnon_ReagentBankButton#4]
Bagnon recently had an API update, so now ReagentBankButton has an error on load:
```
46x Bagnon_ReagentBankButton/main.lua:158: hooksecurefunc(): ListMenuButtons is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Bagnon_ReagentBankButton/main.lua"]:158: in main chunk

Locals:
```

**Comment by LudiusMaximus** [comment]
Thanks for the info! It turns out that from Bagnon 10.2.10 on, it implements its own Reagent Bank Menu Button. Thus, this plugin here is no longer needed I would think. :-)
